In [3]:
## Read a comma seperated value 

x = input("Enter the values")
lst = x.split(',')
t = tuple(lst)
print(lst)
print(t)

Enter the valuesA,B,C,D,E
['A', 'B', 'C', 'D', 'E']
('A', 'B', 'C', 'D', 'E')


In [12]:
import numpy as np 
a = np.array([(1,2,3,4,5),(12,23,34,45,56)])
print(a)
#print(a.ndim)

print(a.flatten())
#print(a.ndim)


print(a.ravel())
#print(a.ndim)

[[ 1  2  3  4  5]
 [12 23 34 45 56]]
[ 1  2  3  4  5 12 23 34 45 56]
[ 1  2  3  4  5 12 23 34 45 56]
