In [5]:
import numpy as np
ls = np.array([1,2,3,4,5,6,7,8,9])

print(ls.reshape(3,3))
print(ls)
print(ls.shape)
print("-------------------------------")
print(ls.resize(3,3))
print(ls)
print(ls.shape)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]
(9,)
-------------------------------
None
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [18]:
## Print pyramid 

def pyr(n):
    for i in range(0,n):
        for j in range(0,i+1):
            print("A", end =' ')
        print('\r')    

In [19]:
pyr(5)

A 
A A 
A A A 
A A A A 
A A A A A 


In [27]:
print("Hi welcome", end = " ")
print("Hi everyone")

Hi welcome Hi everyone
