In [2]:
## Create a numpy array 

import numpy as np 

a = [1,2,3,4,5]

b = np.array(a)
type(b)


numpy.ndarray

In [3]:
a = (1,2,3,4,5)

b = np.array(a)
type(b)


numpy.ndarray

In [4]:
a = {1,2,3,4,5}

b = np.array(a)
type(b)


numpy.ndarray

In [8]:
## while loop : Continue execution as long as the condition is true 

a = 1

while a <= 20: 
    print(a)
    a = a+1



1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20


In [7]:
## For loop 

a = [10,20,30,40,50,60,70,80,90]

for i in a:
    print(i * 2)

20
40
60
80
100
120
140
160
180


In [18]:
a = [1,2,3,4,5]
b = [1,2,3,4,5]

c = np.array([a,b])
c

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [ ]:
## Do while loop : 

# syntax 

do {
    
    Executes the loop
}
Check for while condition 

In [19]:
## Cross product using np 

a = [[1,2],[3,4]]
b = [[5,6],[7,8]]

a = np.array(a)
b = np.array(b)

print(a)
print(b)

np.cross(a,b)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


array([-4, -4])