In [ ]:
## Universal functions

In [1]:
## Matrix product 

import numpy as np 

a = np.arange(0,9).reshape(3,3)
b = np.ones((3,3))
print(a)
print(b)
print(np.dot(a,b))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[ 3.  3.  3.]
 [12. 12. 12.]
 [21. 21. 21.]]


In [2]:
np.sqrt([1,4,9,16,25,36,49])

array([1., 2., 3., 4., 5., 6., 7.])

In [13]:
#gives the remainder
np.mod([0,1,2,3,4,5,6],3)

array([0, 1, 2, 0, 1, 2, 0], dtype=int32)

In [8]:
np.log(0)

C:\Users\AdmiN\AppData\Local\Temp\ipykernel_12496\2933082444.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(0)


-inf

In [14]:
np.log([1,2,3,4,5])

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [23]:
## Aggregate functions

a = np.array([1,2,3,4,5,6,7,8,9])

print(a.sum())
print(a.min())
print(a.max())
print(a.mean())
print(a.std())

45
1
9
5.0
2.581988897471611


In [34]:
## Logical functions

np.all([[True,True],[True,False]])

False

In [49]:
np.array([[True,True],[True,False],[True,False]])

array([[ True,  True],
       [ True, False],
       [ True, False]])

In [50]:
## All - will chek if all the elements are true 

np.all(np.array([[True,True],[True,False],[True,False]]),axis = 1)

array([ True, False, False])

In [36]:
np.all([-3,-4,2,3])

True

In [52]:
## Any - will check for atleast one true value 

np.any(np.array([[True,True],[True,False],[False,False]]),axis = 1)

array([ True,  True, False])

In [59]:
## Logic function 

x = np.array([0,1,2,3,4])

print(np.logical_and( x>1 , x<4 ))  # Both should be true
print(np.logical_or( x>1 , x<4 ))   # Atleast one should be true
print(np.logical_not( x>1 , x<4 ))  # Reverse of outcome

[False False  True  True False]
[ True  True  True  True  True]
[ True  True False False False]


In [69]:
## INdexing 

import numpy as np 

arr = np.arange(21,26)
print(arr)

print(arr[0])
print(arr[-5])
print(arr[1:3])
print(arr[-4:3])

[21 22 23 24 25]
21
21
[22 23]
[22 23]


In [74]:
arr = np.arange(21,30).reshape((3,3))
print(arr)

[[21 22 23]
 [24 25 26]
 [27 28 29]]


In [ ]:
21, 27, 25, 23

In [80]:
print(arr[0,0])
print(arr[2,0])
print(arr[0,1])
print(arr[0,2])

21
27
22
23


In [81]:
arr = np.arange(21,30).reshape((3,3))
print(arr)

[[21 22 23]
 [24 25 26]
 [27 28 29]]


In [82]:
arr[0:2,0:2]

array([[21, 22],
       [24, 25]])

In [83]:
arr[1:3,1:2]

array([[25],
       [28]])

In [84]:
arr[0:2,1:3]

array([[22, 23],
       [25, 26]])

In [85]:
## Array transformations 

# resape & resize : already explained 

## ravel - Convert the 2D array in to 1D

arr = np.arange(21,30).reshape((3,3))
print(arr)

[[21 22 23]
 [24 25 26]
 [27 28 29]]


In [89]:
print(arr.ravel())
print(arr)

[21 22 23 24 25 26 27 28 29]
[[21 22 23]
 [24 25 26]
 [27 28 29]]


In [91]:
print(arr.transpose())
print(arr)

[[21 24 27]
 [22 25 28]
 [23 26 29]]
[[21 22 23]
 [24 25 26]
 [27 28 29]]


In [92]:
## Concatinate 

a = np.arange(21,30).reshape((3,3))
print(a)

b = np.arange(51,60).reshape((3,3))
print(b)

[[21 22 23]
 [24 25 26]
 [27 28 29]]
[[51 52 53]
 [54 55 56]
 [57 58 59]]


In [94]:
np.concatenate((a,b))  #default 

array([[21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [51, 52, 53],
       [54, 55, 56],
       [57, 58, 59]])

In [95]:
np.concatenate((a,b), axis = 0)

array([[21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [51, 52, 53],
       [54, 55, 56],
       [57, 58, 59]])

In [96]:
np.concatenate((a,b), axis = 1)

array([[21, 22, 23, 51, 52, 53],
       [24, 25, 26, 54, 55, 56],
       [27, 28, 29, 57, 58, 59]])

In [97]:
np.stack((a,b))

array([[[21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]],

       [[51, 52, 53],
        [54, 55, 56],
        [57, 58, 59]]])

In [99]:
np.column_stack((a,b))

array([[21, 22, 23, 51, 52, 53],
       [24, 25, 26, 54, 55, 56],
       [27, 28, 29, 57, 58, 59]])

In [100]:
np.row_stack((a,b))

array([[21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [51, 52, 53],
       [54, 55, 56],
       [57, 58, 59]])

In [101]:
np.hstack((a,b))

array([[21, 22, 23, 51, 52, 53],
       [24, 25, 26, 54, 55, 56],
       [27, 28, 29, 57, 58, 59]])

In [102]:
np.vstack((a,b))

array([[21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [51, 52, 53],
       [54, 55, 56],
       [57, 58, 59]])

In [107]:
## Split

x = np.arange(9)
print(x)
np.split(x,3)

[0 1 2 3 4 5 6 7 8]


[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [111]:
# hsplit 

a = np.arange(16).reshape((4,4))
print(a)
np.hsplit(a,2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [112]:
# vsplit 
a = np.arange(16).reshape((4,4))
print(a)
np.vsplit(a,2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]