In [1]:
## Simple calculator using python 

## take input of 2 numbers from user 
## take input of operation from user (add, subt, mult, divi)
## give the output


def add(x,y):
    return x+y
def subt(x,y):
    return x-y
def multi(x,y):
    return x*y
def divi(x,y):
    return x/y

print(" Select the operation")
print("1- Add, 2- Sub, 3-Mult, 4- Div")

while True:
    inp = input(" Enter choice 1,2,3,4")
    
    if inp in ('1','2','3','4'):
        n1 = float(input("Enter first number"))
        n2 = float(input("Enter first number"))
        
        if inp =='1':
            print(add(n1,n2))
        elif inp =='2':
            print(subt(n1,n2))
        elif inp =='3':
            print(multi(n1,n2))
        elif inp =='4':
            print(divi(n1,n2))
            
        next = input("Do you want to do another calclutation ?? Y/N")
        
        if next == 'N':
            break
    else:
        print("Not a valid input")

 Select the operation
1- Add, 2- Sub, 3-Mult, 4- Div
 Enter choice 1,2,3,43
Enter first number12
Enter first number34
408.0
Do you want to do another calclutation ?? Y/NY
 Enter choice 1,2,3,42
Enter first number43
Enter first number12
31.0
Do you want to do another calclutation ?? Y/NY
 Enter choice 1,2,3,44
Enter first number42
Enter first number21
2.0
Do you want to do another calclutation ?? Y/NN


In [2]:
## Numpy 

!pip install numpy

In [3]:
import numpy as np

In [8]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'Bytes0',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'Datetime64',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Str0',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'Uint64',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_version__',
 '__loader__',


In [ ]:
## Create a np array 

In [13]:
a = [1,2,3,4,5]
type(a)

n = np.array(a)
print(n)
type(n)

[1 2 3 4 5]


numpy.ndarray

In [14]:
a = (1,2,3,4,5)
type(a)

n = np.array(a)
print(n)
type(n)

[1 2 3 4 5]


numpy.ndarray

In [15]:
a = {1,2,3,4,5}
type(a)

n = np.array(a)
print(n)
type(n)

{1, 2, 3, 4, 5}


numpy.ndarray

In [16]:
a = {'a':1,'b':2}
type(a)

n = np.array(a)
print(n)
type(n)

{'a': 1, 'b': 2}


numpy.ndarray

In [30]:
## Attributes of nd array

a = [10,20,30,40,50,10,20,30,40,50.6,'c16']
type(a)

n = np.array(a)
print(n)
type(n)

print('--------- Attributes ------------')
print(n.shape)
print(n.size)
print(n.ndim)
print(n.dtype)
print(n.itemsize)


['10' '20' '30' '40' '50' '10' '20' '30' '40' '50.6' 'c16']
--------- Attributes ------------
(11,)
11
1
<U32
128


In [31]:
## Attributes of nd array

a = [[10,20,30],[40,50,10],[20,30,40],[50.6,12,'c16']]
type(a)

n = np.array(a)
print(n)
type(n)

print('--------- Attributes ------------')
print(n.shape)
print(n.size)
print(n.ndim)
print(n.dtype)
print(n.itemsize)


[['10' '20' '30']
 ['40' '50' '10']
 ['20' '30' '40']
 ['50.6' '12' 'c16']]
--------- Attributes ------------
(4, 3)
12
2
<U32
128


In [33]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [34]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [36]:
np.arange(0,20,3)

array([ 0,  3,  6,  9, 12, 15, 18])

In [37]:
np.linspace(0,20,3)

array([ 0., 10., 20.])

In [46]:
## Copy 

a = np.array([1,2,3,4,5])
print(id(a))

b = np.array([1,2,3,4,5])
print(id(b))

c = a

d = a.copy()

print(id(c))
print(id(d))


1546125478192
1546125488272
1546125478192
1546125479728


In [48]:
## Arithmetic operations 

a = np.array([10,20,30,40])
b = np.array([1,2,3,4])

print(a+b)
print(a-b)
print(a*b)
print(a/b)

[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]
[10. 10. 10. 10.]


In [59]:
## reshape and resize 

a = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

print(a.reshape(4,3))  # change the shape but not the original array 
print(a)
print(a.shape)
print('-------------------------------------')
print(a.resize(4,3))  # change the original array
print(a)
print(a.shape)


## Matrix prod

np.dot(a,a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)
-------------------------------------
None
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)


ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)