In [5]:
import numpy as np
ls = np.array([1,2,3,4,5,6,7,8,9])

print(ls.reshape(3,3))
print(ls)
print(ls.shape)
print("-------------------------------")
print(ls.resize(3,3))
print(ls)
print(ls.shape)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]
(9,)
-------------------------------
None
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
